- name: "Add users to the system, if they do not exist"
  ansible.builtin.include_tasks: add_user.yml
  loop: "{{ cfg_users_to_add }}"
  loop_control:
    loop_var: cfg_user
  when: cfg_users_to_add | length > 0

- name: "Remove users from the system, as required"
  ansible.builtin.group:
    name: "{{ cfg_user.user_name }}"
    state: absent
  become: true
  become_user: root
  loop: "{{ cfg_users_to_remove }}"
  loop_control:
    loop_var: cfg_user
  when: cfg_users_to_remove | length > 0

