- name: "Check if user '{{ user_name }}' exists on the system"
  ansible.builtin.include_tasks: check_user_exists.yml

- name: "Add user '{{ user_name }}' to system"
  ansible.builtin.include_tasks: user_add.yml

- name: "Set user '{{ user_name }}' password via prompt"
  ansible.builtin.include_tasks: user_password.yml
  when: set_initial_user_password

- name: "Add user '{{ user_name }}' to specified groups"
  ansible.builtin.include_tasks: user_groups.yml
  when: user_groups is defined

- name: "Create home dir for user '{{ user_name }}'"
  ansible.builtin.include_tasks: create_home_dir.yml
  when: create_home_dir

