# FreeBSD adduser command does not support creating user with "system" UID
- name: "Search the /etc/passwd file to find an available 'system user' UID"
  block:
    - name: "Create '{{ script_name }}.sh' helper script"
      ansible.builtin.template:
        dest: "{{ script_path }}"
        src: "{{ script_name }}.j2"
        owner: 'root'
        mode: '755'
        force: true
    - name: "Find first available UID in the range of {{ min_uid }} to {{ max_uid }}"
      ansible.builtin.command:
        cmd: "{{ script_path }} '{{ min_uid }}' '{{ max_uid }}'"
      register: freebsd_found_system_user_uid
  vars:
    script_name: 'find_first_avail_uid_in_range'
    script_path: "/tmp/{{ script_name }}.sh"
    min_uid: '501'
    max_uid: '999'
  become: true
  become_user: root
  when: ansible_os_family == "FreeBSD"

