- name: "Prompt and set new user '{{ user_name }}' password"
  block:
    - name: "Get user '{{ user_name }}' password, via shell prompt"
      ansible.builtin.pause:
        prompt: "Enter the new password for user '{{ user_name }}'"
        echo: true
      register: new_password
    - name: "Set user '{{ user_name }}' password, using user-input + random-salt"
      ansible.builtin.user:
        name: "{{ user_name }}"
        password: "{{ new_password.user_input | password_hash(password_hash_algorithm) }}"
        create_home: false
      become: true
      become_user: root
  when: user_exists is changed

