- name: "Create '/home/{{ user_name }}', and set correct permissions on it"
  ansible.builtin.file:
    path: "/home/{{ user_name }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '710'
    state: directory
  become: true
  become_user: root

